name: Deploy to production

# Controls when the action will run. 
on:
  # This action can only be manually triggered
  workflow_dispatch:

jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2

      - name: Git fetch and unshallow
        run: git fetch --prune --unshallow

      - name: Copy theme
        uses: Burnett01/rsync-deployments@4.1
        with:
          switches: -rzv --delete
          path: .
          remote_path: ~/www/nosurrenderrunningclub.org/public_html/wp-content/themes/no-surrender-running-club
          remote_host: siteground198.com
          remote_user: u1274-6xdnk6hapvsu
          remote_port: 18765
          remote_key: ${{ secrets.SITEGROUND_PRIVATE_KEY }}

      - name: Purge Cache
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: siteground198.com
          username: u1274-6xdnk6hapvsu
          port: 18765
          key: ${{ secrets.SITEGROUND_PRIVATE_KEY }}
          script: cd ~/www/nosurrenderrunningclub.org/public_html && wp sg purge
